server:
  port: 8080
  servlet:
    context-path:


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:///[postgres]?cloudSqlInstance=url-shortener-417915:us-central1:auto-cute&socketFactory=com.google.cloud.sql.postgres.SocketFactory
    username: postgres
    password: spoon
    hikari:
      data-source-properties:
        socketFactory: com.google.cloud.sql.postgres.SocketFactory
        cloudSqlInstance: url-shortener-417915:us-central1:auto-cute

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp-relay.gmail.com
    port: 587
    username: conorlynam1234@gmail.com
    password: kzyp uioh nyxg exlh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    debug: true
