server:
  servlet:
    context-path:

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql:///postgres
    username: ${_DB_NAME}
    password: ${_DB_PASS}
    hikari:
      data-source-properties:
        socketFactory: com.google.cloud.sql.postgres.SocketFactory
        cloudSqlInstance: url-shortener-417915:europe-west1:bounty

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp-relay.gmail.com
    port: 587
    username: ${_USER_NAME}
    password: ${_APP_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    debug: true
