version: '3.1'

networks:
  default:
    driver: bridge

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: spoon
      POSTGRES_DB: postgres
      POSTGRES_HOST: postgres
      POSTGRES_HOST_AUTH_METHOD: trust

  api:
    container_name: automated-cuteness
    image: automated-cuteness:latest
    build:
      context: .
    environment:
      - host=db
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: no

#  pgadmin:
#    container_name: pgadmin4
#    image: dpage/pgadmin4
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: root
#    ports:
#      - "5050:80"
